
/**
* CounterHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* vendredi 15 mai 2020 17 h 53 WET
*/


// Counter.idl
abstract public class CounterHelper
{
  private static String  _id = "IDL:Counter:1.0";

  public static void insert (org.omg.CORBA.Any a, Counter that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Counter extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (CounterHelper.id (), "Counter");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Counter read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CounterStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Counter value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Counter narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Counter)
      return (Counter)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _CounterStub stub = new _CounterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Counter unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Counter)
      return (Counter)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _CounterStub stub = new _CounterStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
