
/**
* Counter.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* vendredi 15 mai 2020 17 h 53 WET
*/


// Counter.idl
public interface Counter extends CounterOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Counter
