
/**
* Horloge.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* vendredi 5 juin 2020 14 h 31 WET
*/

public interface Horloge extends HorlogeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Horloge
