
/**
* HorlogePOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* vendredi 5 juin 2020 14 h 31 WET
*/

public class HorlogePOATie extends HorlogePOA
{

  // Constructors

  public HorlogePOATie ( HorlogeOperations delegate ) {
      this._impl = delegate;
  }
  public HorlogePOATie ( HorlogeOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public HorlogeOperations _delegate() {
      return this._impl;
  }
  public void _delegate (HorlogeOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String afficher ()
  {
    return _impl.afficher();
  } // afficher

  public String alarme (String wakeup)
  {
    return _impl.alarme(wakeup);
  } // alarme

  private HorlogeOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class HorlogePOATie
