
/**
* HorlogeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* vendredi 5 juin 2020 14 h 31 WET
*/

public final class HorlogeHolder implements org.omg.CORBA.portable.Streamable
{
  public Horloge value = null;

  public HorlogeHolder ()
  {
  }

  public HorlogeHolder (Horloge initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HorlogeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HorlogeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HorlogeHelper.type ();
  }

}
