
/**
* HorlogeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Horloge.idl
* vendredi 5 juin 2020 14 h 31 WET
*/

public interface HorlogeOperations 
{
  String afficher ();
  String alarme (String wakeup);
} // interface HorlogeOperations
