
/**
* CounterOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Counter.idl
* vendredi 15 mai 2020 10 h 13 WET
*/


// Counter.idl
public interface CounterOperations 
{
  int value ();
  void inc ();
  void dec ();
} // interface CounterOperations
